import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import "./globals.css";
import Link from "next/link";
import Footer from "@/components/Footer";


export const metadata = {
  title: "Rabbit hole",
  description: "Generated by The DREAMTEAM",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <Link href="/">Home</Link>
          <Link href="/tv&film">Tv & Film</Link>
          <Link href="/profile">Profile</Link>
          <Link href="/about">About</Link>
          <SignedOut>
            <SignInButton />
          </SignedOut>
          <SignedIn>
            <UserButton />
          </SignedIn>
          {children}
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
